using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            //Problems from: projecteuler.net

            try
            {
                //Problem 2: 
                Console.WriteLine("Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...");
                Console.WriteLine("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");

                //A fibonacci sequence is 0,1,1,2,3,5,8,13,21,34,55,89, etc.... The next number is the sum of the two previous. The base case F(0) = 0 and F(1) = 1. F(n) = F(n-1) + F(n-2)

                int FirstNumber = 1;
                int SecondNumber = 1;
                int CurrentSum = 0;
                int TotalSum = 0;

                //While the current sum of the first and second term is less than 4 million
                while (CurrentSum < 4000000)
                {
                    //Find the current sum
                    CurrentSum = FirstNumber + SecondNumber;

                    //If there is no remainder it is divisible by 2 and we add it to the sum
                    if (CurrentSum % 2 == 0)
                        TotalSum += CurrentSum;

                    //Increase the numbers in the sequence
                    FirstNumber = SecondNumber;
                    SecondNumber = CurrentSum;
                }

                Console.WriteLine("Answer : " + TotalSum);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: " + ex.Message);
            }
            finally
            {
                Console.ReadLine();
            }
        }
    }
}
